# Generated by Django 2.2 on 2020-07-11 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_notion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='notion_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NotionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Notion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
