# Generated by Django 2.2 on 2020-07-11 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200711_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notion',
            name='likes',
        ),
        migrations.AddField(
            model_name='notion',
            name='likes',
            field=models.ManyToManyField(related_name='notion_user', through='myapp.NotionLike', to=settings.AUTH_USER_MODEL),
        ),
    ]