# Generated by Django 2.2 on 2020-07-11 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200711_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='notion_user', through='myapp.NotionLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
