# Generated by Django 2.2 on 2020-07-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notion_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notion',
            options={'ordering': ['-id']},
        ),
    ]
